In [6]:
import pandas as pd


In [7]:
raw_csv_data = pd.read_csv(r"C:\Users\ngsng\Downloads\Absenteeism_data.csv")

In [8]:
type(raw_csv_data)

pandas.core.frame.DataFrame

In [9]:
raw_csv_data

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [10]:
df = raw_csv_data.copy()

In [11]:
df

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [27]:
df = df.drop(['ID'], axis =1 )

In [31]:
df = raw_csv_data.copy()

In [33]:
df['Reason for Absence'].min()

0

In [34]:
df['Reason for Absence'].max()

28

In [35]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [36]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [39]:
len(df['Reason for Absence'].unique())

28

In [40]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [41]:
reason_columns = pd.get_dummies(df['Reason for Absence'])

In [44]:
reason_columns['check'].sum(axis =0)

700

In [45]:
reason_columns['check'].unique()

array([1], dtype=int64)

In [49]:
df.columns.values

array(['ID', 'Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [50]:
reason_columns.columns.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [51]:
df =  df.drop(['Reason for Absence'], axis =1)

In [72]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis = 1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis =1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis =1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis =1)

In [76]:
df.columns.values

array(['ID', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [78]:
column_names = ['ID', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2,', 'Reason_3', 'Reason_4']

In [80]:
df.columns = column_names

In [81]:
df.head()

ID        Date  Transportation Expense  Distance to Work  Age  \
0  11  07/07/2015                     289                36   33   
1  36  14/07/2015                     118                13   50   
2   3  15/07/2015                     179                51   38   
3   7  16/07/2015                     279                 5   39   
4  11  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2,  Reason_3  Reason_4  
0                          4         0          0         0         1  
1                          0         0          0         0         0  
2                          2         0          0         0         1  
3                          4         1          0         0         0  
4                          2         0          0         0         1

In [82]:
df_reason_mod = df.copy()

In [84]:
type(df_reason_mod['Date'][0])

str

In [86]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])

In [88]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [90]:
type(df_reason_mod["Date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [91]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   ID                         700 non-null    int64         
 1   Date                       700 non-null    datetime64[ns]
 2   Transportation Expense     700 non-null    int64         
 3   Distance to Work           700 non-null    int64         
 4   Age                        700 non-null    int64         
 5   Daily Work Load Average    700 non-null    float64       
 6   Body Mass Index            700 non-null    int64         
 7   Education                  700 non-null    int64         
 8   Children                   700 non-null    int64         
 9   Pets                       700 non-null    int64         
 10  Absenteeism Time in Hours  700 non-null    int64         
 11  Reason_1                   700 non-null    uint8         
 12  Reason_2

In [92]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [93]:
df_reason_mod['Date'][0].month

7

In [116]:
list_months = []
list_months

[]

In [117]:
df_reason_mod.shape

(700, 15)

In [118]:
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [119]:
len(list_months)

700

In [120]:
df_reason_mod['Month Value'] = list_months

In [121]:
df_reason_mod.head(20)

ID       Date  Transportation Expense  Distance to Work  Age  \
0   11 2015-07-07                     289                36   33   
1   36 2015-07-14                     118                13   50   
2    3 2015-07-15                     179                51   38   
3    7 2015-07-16                     279                 5   39   
4   11 2015-07-23                     289                36   33   
5    3 2015-10-07                     179                51   38   
6   10 2015-07-17                     361                52   28   
7   20 2015-07-24                     260                50   36   
8   14 2015-06-07                     155                12   34   
9    1 2015-07-13                     235                11   37   
10  20 2015-07-20                     260                50   36   
11  20 2015-07-14                     260                50   36   
12  20 2015-07-15                     260                50   36   
13   3 2015-07-15                     179                51   38   
14   3 2015-07-15                     179                51   38   
15  24 2015-07-17                     246                25   41   
16   3 2015-07-17                     179                51   38   
17   3 2015-07-27                     179                51   38   
18   6 2015-07-30                     189                29   33   
19  33 2015-05-08                     248                25   47   

    Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                   239.554               30          1         2     1   
1                   239.554               31          1         1     0   
2                   239.554               31          1         0     0   
3                   239.554               24          1         2     0   
4                   239.554               30          1         2     1   
5                   239.554               31          1         0     0   
6                   239.554               27          1         1     4   
7                   239.554               23          1         4     0   
8                   239.554               25          1         2     0   
9                   239.554               29          3         1     1   
10                  239.554               23          1         4     0   
11                  239.554               23          1         4     0   
12                  239.554               23          1         4     0   
13                  239.554               31          1         0     0   
14                  239.554               31          1         0     0   
15                  239.554               23          1         0     0   
16                  239.554               31          1         0     0   
17                  239.554               31          1         0     0   
18                  239.554               25          1         2     2   
19                  205.917               32          1         2     1   

    Absenteeism Time in Hours  Reason_1  Reason_2,  Reason_3  Reason_4  \
0                           4         0          0         0         1   
1                           0         0          0         0         0   
2                           2         0          0         0         1   
3                           4         1          0         0         0   
4                           2         0          0         0         1   
5                           2         0          0         0         1   
6                           8         0          0         0         1   
7                           4         0          0         0         1   
8                          40         0          0         1         0   
9                           8         0          0         0         1   
10                          8         1          0         0         0   
11                          8         1          0         0         0   
12                          8        

In [123]:
df_reason_mod['Date'][699].weekday()

3

In [124]:
df_reason_mod['Date'][699]

Timestamp('2018-05-31 00:00:00')

In [126]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [127]:
df_reason_mod['Date of the week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [128]:
df_reason_mod.head()

ID       Date  Transportation Expense  Distance to Work  Age  \
0  11 2015-07-07                     289                36   33   
1  36 2015-07-14                     118                13   50   
2   3 2015-07-15                     179                51   38   
3   7 2015-07-16                     279                 5   39   
4  11 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2,  Reason_3  Reason_4  \
0                          4         0          0         0         1   
1                          0         0          0         0         0   
2                          2         0          0         0         1   
3                          4         1          0         0         0   
4                          2         0          0         0         1   

   Month Value  Date of the week  
0            7                 1  
1            7                 1  
2            7                 2  
3            7                 3  
4            7                 3

In [129]:
df_reason_date_mod = df_reason_mod.copy()

In [131]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [133]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [134]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [136]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [137]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

In [140]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [144]:
df_reason_date_mod['Education']  = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [142]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [145]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [146]:
df_preprocessed = df_reason_date_mod.copy()
df_preprocessed.head(10)

ID       Date  Transportation Expense  Distance to Work  Age  \
0  11 2015-07-07                     289                36   33   
1  36 2015-07-14                     118                13   50   
2   3 2015-07-15                     179                51   38   
3   7 2015-07-16                     279                 5   39   
4  11 2015-07-23                     289                36   33   
5   3 2015-10-07                     179                51   38   
6  10 2015-07-17                     361                52   28   
7  20 2015-07-24                     260                50   36   
8  14 2015-06-07                     155                12   34   
9   1 2015-07-13                     235                11   37   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   
5                  239.554               31          0         0     0   
6                  239.554               27          0         1     4   
7                  239.554               23          0         4     0   
8                  239.554               25          0         2     0   
9                  239.554               29          1         1     1   

   Absenteeism Time in Hours  Reason_1  Reason_2,  Reason_3  Reason_4  \
0                          4         0          0         0         1   
1                          0         0          0         0         0   
2                          2         0          0         0         1   
3                          4         1          0         0         0   
4                          2         0          0         0         1   
5                          2         0          0         0         1   
6                          8         0          0         0         1   
7                          4         0          0         0         1   
8                         40         0          0         1         0   
9                          8         0          0         0         1   

   Month Value  Date of the week  
0            7                 1  
1            7                 1  
2            7                 2  
3            7                 3  
4            7                 3  
5           10                 2  
6            7                 4  
7            7                 4  
8            6                 6  
9            7                 0